sudo: required
services:
  - docker

before_install:
  - docker build -t timwheeler/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timwheeler/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-686693736580"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"